format = """
[ \uf31b ](bg:#fbfbfb fg:#2c77bf)\
$username\
$conda\
$python\
[](bg:#2c77bf fg:#fbfbfb)\
[ ](bg:#2c77bf fg:#ffffff)\
$directory\
[](fg:#2c77bf bg:#e5fa6b)\
$git_branch\
$git_status\
[](fg:#e5fa6b bg:#f79451)\
$nodejs\
$rust\
$golang\
$php\
$typst\
[ ](fg:#f79451)\
\n$character"""


[username]
format = '[[$user ](bg:#fbfbfb fg:#2c77bf)]($style)'
disabled = false
show_always = true

[character]
success_symbol = '[❯❯](fg:39) '
error_symbol = '[❯❮️](fg:198) '

[python]
style = "bg:#fbfbfb fg:#2c77bf"
format = '[${pyenv_prefix}(\($virtualenv\) )]($style)'

[conda]
format = '[[\($environment\) ](fg:#c9002f bg:#fbfbfb)]($style)'

[directory]
style = "fg:#ffffff bg:#2c77bf"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "


[git_branch]
symbol = ""
style = "bg:#e5fa6b"
format = '[[ $symbol $branch ](fg:#1e3548 bg:#e5fa6b)]($style)'

[git_status]
style = "bg:#e5fa6b"
format = '[[($all_status$ahead_behind )](fg:#1e3548 bg:#e5fa6b)]($style)'

[nodejs]
symbol = ""
style = "bg:#f79451"
format = '[[ $symbol ($version) ](fg:#1e3548 bg:#f79451)]($style)'

[typst]
symbol = ""
style = "bg:#f79451"
format = '[[ $symbol ($version) ](fg:#1e3548 bg:#f79451)]($style)'

[rust]
symbol = ""
style = "bg:#f79451"
format = '[[ $symbol ($version) ](fg:#1e3548 bg:#f79451)]($style)'

[golang]
symbol = ""
style = "bg:#f79451"
format = '[[ $symbol ($version) ](fg:#1e3548 bg:#f79451)]($style)'

[php]
symbol = ""
style = "bg:#f79451"
format = '[[ $symbol ($version) ](fg:#1e3548 bg:#f79451)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'
